### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by holiman** [tintinweb/ethereum-dasm#10]
First when I installed it, along with mythril, I got this: 
```
#python3 -m ethereum_dasm -a 0x44919b8026f38d70437a8eb3be47b06ab1c3e4bf  # verify installatio
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 737, in main
    EVMDasmPrinter.basicblocks_detailed_tabulate(contract.disassembly,
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 80, in disassembly
    self._evmcode.disassemble(bytecode=self.bytecode)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 285, in disassemble
    self.analyze_dynamic()  # dynamic would be sufficient
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 504, in analyze_dynamic
    symgraph = symbolic_execute(code=self.contract.bytecode, address=self.contract.address)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/symbolic/mythril.py", line 208, in symbolic_execute
    contract = ETHContract(code)
  File "/home/martin/.local/lib/python3.6/site-packages/mythril/ether/ethcontract.py", line 20, in __init__
    self.disassembly = Disassembly(code, enable_online_lookup=enable_online_lookup)
  File "/home/martin/.local/lib/python3.6/site-packages/mythril/disassembler/disassembly.py", line 50, in __init__
    signatures.write()  # store resolved signatures (potentially resolved online)
  File "/home/martin/.local/lib/python3.6/site-packages/mythril/support/signatures.py", line 127, in write
    open(path, "w").close()
FileNotFoundError: [Errno 2] No such file or directory: '/home/martin/.mythril/signatures.json'

```
I found the file and downloaded it manually to the right location. Then I got this: 

```
#python3 -m ethereum_dasm -a 0x44919b8026f38d70437a8eb3be47b06ab1c3e4bf  # verify installatio
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 737, in main
    EVMDasmPrinter.basicblocks_detailed_tabulate(contract.disassembly,
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 80, in disassembly
    self._evmcode.disassemble(bytecode=self.bytecode)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 285, in disassemble
    self.analyze_dynamic()  # dynamic would be sufficient
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 542, in analyze_dynamic
    cdl_offset = get_z3_value(state.mstate.stack[-1])  # get last item from stack (=offset)
NameError: name 'get_z3_value' is not defined

```

**Comment by holiman** [comment]
And these

```
[~/workspace/ethereum-dasm]
#echo "0x60406040"| python3 -m ethereum_dasm 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 737, in main
    EVMDasmPrinter.basicblocks_detailed_tabulate(contract.disassembly,
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 80, in disassembly
    self._evmcode.disassemble(bytecode=self.bytecode)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 268, in disassemble
    self.instructions = list(self.disassembler.disassemble(bytecode))
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/asm/disassembler.py", line 42, in disassemble
    iter_bytecode = iter(utils.str_to_bytes(bytecode))
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/utils/data.py", line 40, in str_to_bytes
    return bytes.fromhex(s.replace("0x", ""))
ValueError: non-hexadecimal number found in fromhex() arg at position 8
[~/workspace/ethereum-dasm]
#echo "60406040"| python3 -m ethereum_dasm 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 737, in main
    EVMDasmPrinter.basicblocks_detailed_tabulate(contract.disassembly,
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 80, in disassembly
    self._evmcode.disassemble(bytecode=self.bytecode)
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/evmdasm.py", line 268, in disassemble
    self.instructions = list(self.disassembler.disassemble(bytecode))
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/asm/disassembler.py", line 42, in disassemble
    iter_bytecode = iter(utils.str_to_bytes(bytecode))
  File "/home/martin/workspace/ethereum-dasm/ethereum_dasm/utils/data.py", line 40, in str_to_bytes
    return bytes.fromhex(s.replace("0x", ""))
ValueError: non-hexadecimal number found in fromhex() arg at position 8

```

**Comment by holiman** [comment]
For the latter, `echo -n` solved a dangling linebreak which made it into the code

**Comment by tintinweb** [comment]
1. mythril signature file - errors because the `.mythril` directory is missing. mythril mkdirs is in the init code and ethereum-dasm does not. I feel like this should be fixed in mythril at the sigdb write check. - wontfix: mkdir ~/.mythril fixes the issue.
2. get_z3_value - this is because I haven't yet published the decompiler ;p - fixed (dummy func)
3. fixed to also work without `echo -n` -fixed

**Comment by tintinweb** [comment]
installed fixed version as follows:
`mkdir ~/.myhtril`
`pip install --upgrade git+https://github.com/tintinweb/ethereum-dasm.git@master`

let me know if that works for you. 

btw. it's already using [evmdasm](https://github.com/tintinweb/evmdasm) as the instruction registry 👍
