### ISSUE TITLE
Crash when analyzing particular contract

### ISSUE THREAD

**Issue by gsalzer** [tintinweb/ethereum-dasm#12]
`python3 -m ethereum_dasm -a 0x131A99859a8bfa3251D899F0675607766736FFaE` crashes in ` mythril/laser/ethereum/state.py` with an `Index error`.
When deactivating dynamic analysis it works, i.e.,
`python3 -m ethereum_dasm -D -a 0x131A99859a8bfa3251D899F0675607766736FFaE` runs fine.
So probably rather a mythril issue.

**Comment by tintinweb** [comment]
Hi @gsalzer,

appears to be a mythril issue. please try running mythril on the contract and check if it also fails and file an issue in their project. they're usually pretty quick when it comes to responding to such issues.

feel free to link the pr here for reference.

cheers,
tin

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/usr/local/lib/python3.6/dist-packages/ethereum_dasm/evmdasm.py", line 639, in main
    console.EVMDasmPrinter.basicblocks_detailed_tabulate(contract.disassembly,
  File "/usr/local/lib/python3.6/dist-packages/ethereum_dasm/evmdasm.py", line 77, in disassembly
    self._evmcode.disassemble(bytecode=self.bytecode)
  File "/usr/local/lib/python3.6/dist-packages/ethereum_dasm/evmdasm.py", line 292, in disassemble
    self.analyze_dynamic()  # dynamic would be sufficient
  File "/usr/local/lib/python3.6/dist-packages/ethereum_dasm/evmdasm.py", line 511, in analyze_dynamic
    symgraph = symbolic_execute(code=self.contract.bytecode, address=self.contract.address)
  File "/usr/local/lib/python3.6/dist-packages/ethereum_dasm/symbolic/mythril.py", line 209, in symbolic_execute
    sym = SymExecWrapper(contract=contract, address=address, strategy="dfs")
  File "/usr/local/lib/python3.6/dist-packages/mythril/analysis/symbolic.py", line 38, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 67, in sym_exec
    execute_message_call(self, main_address)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/transaction/symbolic.py", line 34, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 101, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/svm.py", line 122, in execute_state
    new_global_states = Instruction(op_code, self.dynamic_loader).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 86, in evaluate
    return instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 52, in wrapper
    global_state
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 39, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/instructions.py", line 1212, in delegatecall_
    self.dynamic_loader)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/call.py", line 25, in get_call_parameters
    memory_input_offset, memory_input_size, memory_out_offset, memory_out_size = global_state.mstate.pop(4)
  File "/usr/local/lib/python3.6/dist-packages/mythril/laser/ethereum/state.py", line 162, in pop
    raise IndexError()
IndexError
```
