### ISSUE TITLE
crash on -L -a 0x879A8C7C3FD36338E6909e38C724B508801c01B0

### ISSUE THREAD

**Issue by gsalzer** [tintinweb/ethereum-dasm#14]
```
$ python3 -m ethereum_dasm -L -a 0x879A8C7C3FD36338E6909e38C724B508801c01B0
ERROR   - invalid instruction: PUSH4
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.6/site-packages/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/home/user/.local/lib/python3.6/site-packages/ethereum_dasm/evmdasm.py", line 636, in main
    console.EVMDasmPrinter.listing(contract.disassembly)
  File "/home/user/.local/lib/python3.6/site-packages/ethereum_dasm/output/console.py", line 31, in listing
    for i, nm in enumerate(disasm):
TypeError: 'EvmCode' object is not iterable
```
The program crashes independently of any other flags; `-L` is the crucial one.

**Comment by tintinweb** [comment]
thx @gsalzer 👍 

merged to master. use  `pip install "git+https://github.com/tintinweb/ethereum-dasm.git@master" --upgrade` if you want to try it before I push a new version to pypi.
