### ISSUE TITLE
crash when using -A without -a

### ISSUE THREAD

**Issue by gsalzer** [tintinweb/ethereum-dasm#16]
Apparently ABI reconstruction (option `-A`) takes the contract address from the commandline option `-a`. If the hex code is provided verbatim or in a file, this address is missing and the program generates a dump:

```
reconstructed ABI:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.6/site-packages/ethereum_dasm/__main__.py", line 7, in <module>
    evmdasm.main()
  File "/home/user/.local/lib/python3.6/site-packages/ethereum_dasm/evmdasm.py", line 659, in main
    print(contract.guess_abi())
  File "/home/user/.local/lib/python3.6/site-packages/ethereum_dasm/evmdasm.py", line 104, in guess_abi
    raise Exception("address required.")
Exception: address required.

```

**Comment by tintinweb** [comment]
Hi @gsalzer,

atm this is by intention as the ABI guessing code is quite experimental and not yet prepared to work without an address (it is basically checking an online source first and then merging this info with what we derive from the disassembly). Once I finish the implementation it should also work without having to provide the correct address.

I'll turn your issue into a feature request. 

cheers,
tin
