### ISSUE TITLE
Error during installation via pip

### ISSUE THREAD

**Issue by medvedev1088** [tintinweb/ethereum-dasm#5]
Trying to install it via pip gives this error:
```
$ pip install ethereum-dasm
Collecting ethereum-dasm
  Using cached https://files.pythonhosted.org/packages/c7/ed/f021a18576928d5f0e807bc43a62c7866cf9a8e730221363778e30d32392/ethereum-dasm-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t0/y38g0z2s6jqcnwp8452j026h0000gp/T/pip-install-8x_vczkr/ethereum-dasm/setup.py", line 23, in <module>
        long_description=read("README.rst") if os.path.isfile("README.rst") else read("README.md"),
      File "/private/var/folders/t0/y38g0z2s6jqcnwp8452j026h0000gp/T/pip-install-8x_vczkr/ethereum-dasm/setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/t0/y38g0z2s6jqcnwp8452j026h0000gp/T/pip-install-8x_vczkr/ethereum-dasm/README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t0/y38g0z2s6jqcnwp8452j026h0000gp/T/pip-install-8x_vczkr/ethereum-dasm/
```

**Comment by tintinweb** [comment]
published to pypi. try:
```
pip install "ethereum-dasm[abidecoder]"
python -m ethereum_dasm --help
```
